# -*- coding: utf-8 -*-
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def make_entry(portal, name, group, path, shape, api, columns, sso=None):
    buttons = {
        "crud": ["query", "reset", "create", "import", "export", "batchDelete"],
        "gis": ["query", "reset"],
        "sso": ["open"],
        "screen": ["fullscreen"],
        "workbench": ["refresh"],
    }.get(shape, ["query"])
    return {
        "portal": portal,
        "name": name,
        "group": group,
        "path": path,
        "shape": shape,
        "api": api,
        "columns": [{"prop": c, "label": c} for c in columns],
        "buttons": buttons,
        "ssoUrl": sso,
        "status": "planned",
    }


GOV_DEFS = [
    ("工作台", "工作台", "/gov/workbench", "workbench", "/todos", ["title", "status", "bizType"]),
    ("待办列表", "工作台", "/gov/workbench/todos", "workbench", "/todos", ["title", "status", "bizType", "linkPath"]),
    ("领导驾驶舱", "工作台", "/gov/cockpit", "screen", "/analytics/cockpit", []),
    ("政策管理", "质量安全", "/gov/quality/policies", "crud", "/quality/policies", ["name", "fileName", "publishDate"]),
    ("检测机构", "质量安全", "/gov/quality/labs", "crud", "/quality/labs", ["name", "labType", "regionName", "createdAt"]),
    (
        "质量抽检",
        "质量安全",
        "/gov/quality/inspections",
        "crud",
        "/quality/inspections",
        ["year", "quarter", "level", "enterpriseName", "species", "labName", "result", "unqualified", "inspectedAt"],
    ),
    (
        "质量整改",
        "质量安全",
        "/gov/quality/rectifications",
        "crud",
        "/quality/rectifications",
        ["enterpriseName", "species", "labName", "result", "status"],
    ),
    (
        "质量监管统计",
        "质量安全",
        "/gov/quality/stats-mgmt",
        "crud",
        "/quality/stats-records",
        ["year", "quarter", "regionName", "level", "enterpriseCount", "sampleCount", "passCount", "failCount"],
    ),
    (
        "标识审核",
        "追溯标识",
        "/gov/trace/applies",
        "crud",
        "/trace/applies",
        ["enterpriseName", "regionName", "species", "brand", "applyDate", "status"],
    ),
    (
        "标识分发",
        "追溯标识",
        "/gov/trace/codes",
        "crud",
        "/trace/codes",
        ["adminCode", "enterpriseName", "regionName", "serialCode", "speciesCode", "brand", "applyDate"],
    ),
    (
        "标识统计查询",
        "追溯标识",
        "/gov/trace/label-stats",
        "crud",
        "/trace/label-stats",
        ["labelCode", "enterpriseName", "species", "customer", "dest", "saleDate", "genDate", "status"],
    ),
    ("政策管理", "尾水监管", "/gov/effluent/policies", "crud", "/effluent/policies", ["name", "scope", "publishDate"]),
    (
        "排放水域",
        "尾水监管",
        "/gov/effluent/waters",
        "crud",
        "/effluent/waters",
        ["enterpriseName", "subjectType", "regionName", "zone", "level"],
    ),
    (
        "尾水排放计划",
        "尾水监管",
        "/gov/effluent/plans",
        "crud",
        "/effluent/plans",
        ["county", "township", "village", "enterpriseName", "zone", "planTime", "fileDate", "status"],
    ),
    (
        "养殖主体",
        "主体资源",
        "/gov/party/enterprises",
        "crud",
        "/party/enterprises",
        ["name", "subjectType", "regionName", "projectName", "areaMu", "species"],
    ),
    (
        "用户管理",
        "主体资源",
        "/gov/party/users",
        "crud",
        "/system/users",
        ["username", "realName", "mobile", "roleName", "orgName", "projectName", "source"],
    ),
    ("塘口信息采集", "主体资源", "/gov/party/gis-collect", "gis", "/party/gis/layers", ["name", "auditStatus", "areaMu", "species"]),
    ("渔业信息审核", "主体资源", "/gov/party/gis-audit", "gis", "/party/gis/layers", ["name", "auditStatus", "enterpriseName"]),
    ("渔业资源统计", "主体资源", "/gov/party/gis-stats", "gis", "/analytics/resources", []),
    (
        "病害检测管理",
        "大鲵专项",
        "/gov/specialty/disease-test",
        "crud",
        "/specialty/disease-tests",
        ["applyNo", "applyDate", "applicant", "sampleSource", "purpose", "status"],
    ),
    (
        "育种驯化管理",
        "大鲵专项",
        "/gov/specialty/domestication",
        "crud",
        "/specialty/domestication-plots",
        ["name", "areaMu", "species", "cost", "yieldKg", "profit"],
    ),
    ("资讯类别", "产业资讯", "/gov/cms/categories", "crud", "/cms/categories", ["name", "sortNo"]),
    ("文章资讯", "产业资讯", "/gov/cms/articles", "crud", "/cms/articles", ["title", "category", "recommend", "views", "source"]),
    ("视频资讯", "产业资讯", "/gov/cms/videos", "crud", "/cms/videos", ["title", "category", "url", "views"]),
    ("市场管理", "产业资讯", "/gov/supply/markets", "crud", "/supply/markets", ["name", "region", "lng", "lat"]),
    (
        "行情归集",
        "产业资讯",
        "/gov/supply/prices",
        "crud",
        "/supply/prices",
        ["species", "spec", "price", "unit", "marketId", "priceDate"],
    ),
    (
        "苗种供应",
        "产业资讯",
        "/gov/supply/seed",
        "crud",
        "/supply/listings?category=SEED",
        ["title", "brand", "supplierName", "contact", "phone", "region", "price"],
    ),
    (
        "饲料供应",
        "产业资讯",
        "/gov/supply/feed",
        "crud",
        "/supply/listings?category=FEED",
        ["title", "brand", "supplierName", "contact", "phone", "region", "price"],
    ),
    (
        "渔药供应",
        "产业资讯",
        "/gov/supply/medicine",
        "crud",
        "/supply/listings?category=MEDICINE",
        ["title", "brand", "supplierName", "contact", "phone", "region", "price"],
    ),
    (
        "装备供应",
        "产业资讯",
        "/gov/supply/equip",
        "crud",
        "/supply/listings?category=EQUIP",
        ["title", "brand", "supplierName", "contact", "phone", "region", "price"],
    ),
]

ENT_DEFS = [
    ("工作台", "工作台", "/ent/workbench", "workbench", "/todos", ["title", "status"]),
    ("待办列表", "工作台", "/ent/workbench/todos", "workbench", "/todos", ["title", "status", "bizType"]),
    ("企业大屏", "工作台", "/ent/screen", "screen", "/analytics/enterprise-screen", []),
    ("标识申请", "质量追溯", "/ent/quality/trace-apply", "crud", "/trace/applies", ["species", "brand", "status", "applyDate"]),
    (
        "自主监管",
        "质量追溯",
        "/ent/quality/self-checks",
        "crud",
        "/quality/self-checks",
        ["pondName", "species", "sampleCount", "labName", "result", "report", "checkDate"],
    ),
    (
        "政府监管",
        "质量追溯",
        "/ent/quality/gov-checks",
        "crud",
        "/quality/inspections",
        ["year", "quarter", "level", "species", "labName", "result", "inspectedAt"],
    ),
    ("质量整改", "质量追溯", "/ent/quality/rectifications", "crud", "/quality/rectifications", ["pondName", "species", "status", "content"]),
    (
        "质量监管",
        "质量追溯",
        "/ent/quality/regulation",
        "crud",
        "/quality/inspections",
        ["year", "quarter", "level", "species", "result", "inspectedAt"],
    ),
    ("质量管理", "质量追溯", "/ent/quality/control", "crud", "/quality/inspections", ["species", "result", "source", "inspectedAt"]),
    ("病情测报", "病害防疫", "/ent/sso/bqcb", "sso", None, [], "http://60.165.239.173:9001/homepage/index"),
    (
        "水生动物疾病远程辅助诊断网",
        "病害防疫",
        "/ent/sso/diagnosis",
        "sso",
        None,
        [],
        "http://60.165.239.173:9000/ffcportal",
    ),
    ("巡检记录", "尾水环保", "/ent/effluent/patrols", "crud", "/effluent/patrols", ["title", "result", "status", "createdAt"]),
    ("指挥调度记录", "尾水环保", "/ent/effluent/dispatches", "crud", "/effluent/dispatches", ["title", "status", "feedback"]),
    ("整改记录", "尾水环保", "/ent/effluent/rectifications", "crud", "/effluent/rectifications", ["title", "status", "reply"]),
    ("塘口养殖", "养殖生产", "/ent/breeding/ponds", "crud", "/party/ponds", ["name", "species", "areaMu", "auditStatus"]),
    ("养殖农事", "养殖生产", "/ent/breeding/activities", "crud", "/breeding/activities", ["title", "activityType", "qty", "unit", "occurredAt"]),
    (
        "养殖批次统计",
        "养殖生产",
        "/ent/breeding/batches",
        "crud",
        "/breeding/batches",
        ["pondName", "species", "stockSpec", "stockQty", "stockDate", "endDate", "days", "outSpec", "yieldKg"],
    ),
    (
        "销售信息管理",
        "养殖生产",
        "/ent/breeding/sales",
        "crud",
        "/breeding/sales",
        ["orderNo", "species", "customerName", "orderType", "amount", "weightKg", "soldAt", "status"],
    ),
    (
        "病害检测管理",
        "大鲵专项",
        "/ent/specialty/disease-test",
        "crud",
        "/specialty/disease-tests",
        ["applyNo", "applyDate", "applicant", "sampleSource", "purpose", "status"],
    ),
    (
        "加工管理",
        "大鲵专项",
        "/ent/specialty/processing",
        "crud",
        "/specialty/processing",
        ["materialNo", "purchaseDate", "pondName", "weightKg", "quarantineStatus"],
    ),
    (
        "养殖生产管理",
        "大鲵专项",
        "/ent/specialty/transport",
        "crud",
        "/specialty/transports",
        ["transportNo", "fromAddr", "toAddr", "tempC", "durationH", "sampleStatus"],
    ),
    (
        "育种驯化管理",
        "大鲵专项",
        "/ent/specialty/domestication",
        "crud",
        "/specialty/domestication-logs",
        ["date", "pondName", "feedType", "feedQty", "effect"],
    ),
    (
        "养殖主体信息",
        "我的基地",
        "/ent/base/enterprise",
        "crud",
        "/party/enterprises",
        ["name", "areaMu", "species", "contactName", "contactPhone", "address", "status"],
    ),
    ("塘口信息采集", "我的基地", "/ent/base/gis", "gis", "/party/gis/layers", ["name", "areaMu", "species", "auditStatus"]),
    ("人员管理", "我的基地", "/ent/base/staffs", "crud", "/party/staffs", ["name", "phone", "gender", "post", "status"]),
    ("苗种信息来源", "投入品", "/ent/inputs/seed-info", "crud", "/inputs/items?category=SEED", ["name", "spec", "fcr", "image"]),
    ("饲料信息来源", "投入品", "/ent/inputs/feed-info", "crud", "/inputs/items?category=FEED", ["name", "spec", "fcr", "image"]),
    (
        "渔药信息来源",
        "投入品",
        "/ent/inputs/medicine-info",
        "crud",
        "/inputs/items?category=MEDICINE",
        ["name", "spec", "prescription", "ingredient", "image"],
    ),
    ("苗种供应商", "投入品", "/ent/inputs/seed-supplier", "crud", "/inputs/suppliers?category=SEED", ["name", "contact", "phone", "address"]),
    ("饲料供应商", "投入品", "/ent/inputs/feed-supplier", "crud", "/inputs/suppliers?category=FEED", ["name", "contact", "phone", "address"]),
    (
        "渔药供应商",
        "投入品",
        "/ent/inputs/medicine-supplier",
        "crud",
        "/inputs/suppliers?category=MEDICINE",
        ["name", "contact", "phone", "address"],
    ),
    (
        "设备策略管理",
        "物联中心",
        "/ent/iot/rules",
        "crud",
        "/iot/rules",
        ["name", "deviceName", "pointCode", "operator", "threshold", "enabled"],
    ),
    ("设备控制", "物联中心", "/ent/iot/control", "crud", "/iot/commands", ["deviceId", "command", "result", "detail"]),
    ("视频监控", "物联中心", "/ent/iot/cameras", "crud", "/iot/cameras", ["name", "deviceSerial", "channelNo", "scene"]),
    ("水质监测", "物联中心", "/ent/iot/water-monitor", "crud", "/iot/telemetry", ["deviceId", "pointCode", "value", "unit", "collectedAt"]),
    (
        "水质数据",
        "物联中心",
        "/ent/iot/water-data",
        "crud",
        "/iot/water-lab",
        [
            "permanganate",
            "nitrite",
            "ammonia",
            "alkalinity",
            "salinity",
            "ss",
            "flagellate",
            "diatom",
            "cyanobacteria",
            "protozoa",
            "sampledAt",
        ],
    ),
    ("尾水监测", "物联中心", "/ent/iot/tailwater", "crud", "/iot/telemetry?type=TAILWATER", ["deviceId", "pointCode", "value", "collectedAt"]),
    ("气象监测", "物联中心", "/ent/iot/weather", "crud", "/iot/weather", ["sampledAt", "tempC", "windDir", "windLevel", "humidity", "condition"]),
    ("设备预警", "物联中心", "/ent/iot/alarms", "crud", "/iot/alarms", ["title", "deviceNo", "deviceType", "content", "status", "occurredAt"]),
    (
        "病害预警",
        "物联中心",
        "/ent/disease/alerts",
        "crud",
        "/disease/alerts",
        ["species", "diseaseName", "pondName", "areaMu", "occurredAt", "status"],
    ),
    ("客户信息", "客户账本", "/ent/ledger/customers", "crud", "/ledger/customers", ["name", "contact", "phone", "region", "address"]),
    (
        "合同信息",
        "客户账本",
        "/ent/ledger/contracts",
        "crud",
        "/ledger/contracts",
        ["customerName", "species", "qty", "amount", "paid", "signDate", "status"],
    ),
    ("费用信息", "客户账本", "/ent/ledger/fees", "crud", "/ledger/fees", ["customerName", "contractCount", "totalAmount", "paid", "feeStatus"]),
    (
        "购买历史",
        "客户账本",
        "/ent/ledger/purchase-history",
        "crud",
        "/ledger/purchase-history",
        ["customerName", "orderCount", "totalAmount", "lastOrderAt"],
    ),
    ("客户画像", "客户账本", "/ent/ledger/portrait", "crud", "/ledger/customers", ["name", "phone", "orderCount", "totalAmount"]),
    (
        "手工记账",
        "客户账本",
        "/ent/ledger/manual",
        "crud",
        "/ledger/entries",
        ["month", "seed", "feed", "medicine", "rent", "power", "water", "labor", "other", "total"],
    ),
    ("经营分析", "客户账本", "/ent/ledger/analysis", "crud", "/ledger/analysis", ["month", "income", "cost", "profit"]),
    (
        "售后服务",
        "客户账本",
        "/ent/ledger/after-sales",
        "crud",
        "/ledger/after-sales",
        ["customerName", "orderNo", "feedbackType", "content", "status", "handler"],
    ),
    ("仓库管理", "仓储经营", "/ent/wms/warehouses", "crud", "/wms/warehouses", ["name", "code", "status"]),
    ("仓库设备", "仓储经营", "/ent/wms/equip", "crud", "/wms/warehouse-equip", ["name", "warehouseName", "status"]),
    ("仓库视频", "仓储经营", "/ent/wms/video", "crud", "/iot/cameras?scene=WAREHOUSE", ["name", "deviceSerial", "scene"]),
    ("饲料库存", "仓储经营", "/ent/wms/feed-stock", "crud", "/wms/stocks?category=FEED", ["itemName", "qty", "unit", "warehouseName"]),
    ("入库记录", "仓储经营", "/ent/wms/feed-in", "crud", "/wms/inbounds?category=FEED", ["itemName", "qty", "status", "source"]),
    ("出库记录", "仓储经营", "/ent/wms/feed-out", "crud", "/wms/outbounds?category=FEED", ["itemName", "qty", "status"]),
    ("渔药库存", "仓储经营", "/ent/wms/med-stock", "crud", "/wms/stocks?category=MEDICINE", ["itemName", "qty", "unit", "warehouseName"]),
    ("入库记录", "仓储经营", "/ent/wms/med-in", "crud", "/wms/inbounds?category=MEDICINE", ["itemName", "qty", "status"]),
    ("出库记录", "仓储经营", "/ent/wms/med-out", "crud", "/wms/outbounds?category=MEDICINE", ["itemName", "qty", "status"]),
    ("产品库存", "仓储经营", "/ent/wms/product-stock", "crud", "/wms/stocks?category=PRODUCT", ["itemName", "qty", "unit", "warehouseName"]),
    ("入库记录", "仓储经营", "/ent/wms/product-in", "crud", "/wms/inbounds?category=PRODUCT", ["itemName", "qty", "status", "source"]),
    ("出库记录", "仓储经营", "/ent/wms/product-out", "crud", "/wms/outbounds?category=PRODUCT", ["itemName", "qty", "status"]),
    ("库存盘点", "仓储经营", "/ent/wms/stocktake", "crud", "/wms/stocktakes", ["title", "warehouseId", "status", "remark"]),
    ("销售管理", "流通加工", "/ent/circulation/sales", "crud", "/circulation/sales-orders", ["orderNo", "buyer", "amount", "status"]),
    ("产销对接", "流通加工", "/ent/circulation/match", "crud", "/circulation/sales-orders", ["orderNo", "buyer", "amount", "status"]),
    ("运输信息管理", "流通加工", "/ent/circulation/transports", "crud", "/circulation/transports", ["plateNo", "fromAddr", "toAddr", "status"]),
    (
        "加工信息管理",
        "流通加工",
        "/ent/circulation/processing",
        "crud",
        "/specialty/processing",
        ["materialNo", "pondName", "weightKg", "quarantineStatus"],
    ),
    ("标签打印信息", "流通加工", "/ent/circulation/labels", "crud", "/trace/codes", ["code", "enterpriseId", "status", "boundAt"]),
]

LABELS = {
    "name": "名称",
    "title": "标题",
    "status": "状态",
    "bizType": "业务类型",
    "linkPath": "链接",
    "fileName": "附件文件",
    "publishDate": "发布日期",
    "labType": "检测类型",
    "regionName": "所属区域",
    "createdAt": "创建日期",
    "year": "年度",
    "quarter": "季度",
    "level": "级别",
    "enterpriseName": "主体",
    "species": "品种",
    "labName": "检测机构",
    "result": "检测结果",
    "unqualified": "不合格指标",
    "inspectedAt": "抽检日期",
    "enterpriseCount": "抽检企业数",
    "sampleCount": "抽检样品数",
    "passCount": "合格样品数",
    "failCount": "不合格样品数",
    "brand": "品牌",
    "applyDate": "申请日期",
    "adminCode": "行政编码",
    "serialCode": "养殖企业流水码",
    "speciesCode": "品种代码",
    "labelCode": "追溯标签码",
    "customer": "销售客户",
    "dest": "销售去向",
    "saleDate": "销售日期",
    "genDate": "生成日期",
    "scope": "政策适用范围",
    "subjectType": "主体类型",
    "zone": "水域分区",
    "county": "区县",
    "township": "乡镇",
    "village": "村",
    "planTime": "计划排放时间",
    "fileDate": "备案日期",
    "projectName": "所属项目",
    "areaMu": "养殖面积（亩）",
    "username": "登录名",
    "realName": "真实姓名",
    "mobile": "手机号",
    "roleName": "角色",
    "orgName": "主体/单位",
    "source": "来源",
    "auditStatus": "审核状态",
    "applyNo": "申请编号",
    "applicant": "申请人",
    "sampleSource": "样本来源",
    "purpose": "目的",
    "cost": "成本",
    "yieldKg": "产量",
    "profit": "利润",
    "sortNo": "排序",
    "recommend": "首页推荐",
    "views": "阅读量",
    "category": "类别",
    "url": "链接",
    "lng": "经度",
    "lat": "纬度",
    "spec": "规格",
    "price": "价格",
    "unit": "单位",
    "marketId": "市场",
    "priceDate": "归集日期",
    "supplierName": "供应商",
    "contact": "联系人",
    "phone": "电话",
    "region": "区域",
    "pondName": "塘口",
    "checkDate": "检测日期",
    "report": "检测报告",
    "feedback": "反馈",
    "reply": "回复",
    "content": "内容",
    "activityType": "农事类型",
    "qty": "数量",
    "occurredAt": "发生时间",
    "stockSpec": "投苗规格",
    "stockQty": "投苗数量",
    "stockDate": "投苗日期",
    "endDate": "结束日期",
    "days": "养殖天数",
    "outSpec": "出苗规格",
    "orderNo": "订单编号",
    "customerName": "客户",
    "orderType": "类型",
    "amount": "金额",
    "weightKg": "数量kg",
    "soldAt": "日期",
    "materialNo": "原料编号",
    "purchaseDate": "采购日期",
    "quarantineStatus": "检疫状态",
    "transportNo": "运输编号",
    "fromAddr": "起运地",
    "toAddr": "目的地",
    "tempC": "温度",
    "durationH": "时长",
    "sampleStatus": "抽检",
    "date": "驯化日期",
    "feedType": "饵料类型",
    "feedQty": "投喂量",
    "effect": "效果",
    "contactName": "联系人",
    "contactPhone": "电话",
    "address": "地址",
    "gender": "性别",
    "post": "岗位",
    "fcr": "饵料系数",
    "image": "图片",
    "prescription": "是否处方药",
    "ingredient": "成分",
    "deviceName": "设备名称",
    "pointCode": "参数",
    "operator": "条件",
    "threshold": "阈值",
    "enabled": "启用",
    "deviceId": "设备",
    "command": "指令",
    "detail": "详情",
    "deviceSerial": "序列号",
    "channelNo": "通道",
    "scene": "场景",
    "value": "数值",
    "collectedAt": "采集时间",
    "permanganate": "高锰酸盐",
    "nitrite": "亚硝酸盐",
    "ammonia": "氨氮",
    "alkalinity": "碱度",
    "salinity": "盐度",
    "ss": "悬浮物",
    "flagellate": "鞭藻",
    "diatom": "硅藻",
    "cyanobacteria": "蓝藻",
    "protozoa": "原生动物",
    "sampledAt": "时间",
    "windDir": "风向",
    "windLevel": "风力",
    "humidity": "湿度",
    "condition": "天气现象",
    "deviceNo": "编号",
    "deviceType": "类型",
    "diseaseName": "病名",
    "signDate": "日期",
    "paid": "已付",
    "contractCount": "合同数",
    "totalAmount": "总金额",
    "feeStatus": "费用状态",
    "orderCount": "订单数",
    "lastOrderAt": "最近下单",
    "month": "月份",
    "seed": "苗种",
    "feed": "饲料",
    "medicine": "渔药",
    "rent": "租金",
    "power": "用电",
    "water": "用水",
    "labor": "人工",
    "other": "其他",
    "total": "总预算",
    "income": "收入",
    "profit": "利润",
    "feedbackType": "反馈类型",
    "handler": "处理人",
    "code": "编码",
    "itemName": "品名",
    "warehouseName": "仓库",
    "buyer": "买方",
    "plateNo": "车牌",
    "boundAt": "绑定时间",
    "remark": "备注",
    "warehouseId": "仓库",
    "enterpriseId": "主体ID",
}


def parse_row(row):
    if len(row) == 7:
        return row
    return (*row, None)


def main():
    catalog = {"GOV": [], "ENT": []}
    for row in GOV_DEFS:
        name, group, path, shape, api, cols, sso = parse_row(row)
        catalog["GOV"].append(make_entry("GOV", name, group, path, shape, api, cols, sso))
    for row in ENT_DEFS:
        name, group, path, shape, api, cols, sso = parse_row(row)
        catalog["ENT"].append(make_entry("ENT", name, group, path, shape, api, cols, sso))

    for portal in catalog:
        for e in catalog[portal]:
            for c in e["columns"]:
                c["label"] = LABELS.get(c["prop"], c["prop"])

    lines = [
        "# 10 — 全量对照矩阵\n\n",
        "> 对照源：现网区县/企业菜单；本地 path/shape/api 为仿做目标\n\n",
        "## 区县 GOV\n\n",
        "| liveMenu | group | localPath | shape | api | status |\n|---|---|---|---|---|---|\n",
    ]
    for e in catalog["GOV"]:
        lines.append(f"| {e['name']} | {e['group']} | `{e['path']}` | {e['shape']} | `{e['api']}` | {e['status']} |\n")
    lines.append("\n## 企业 ENT\n\n")
    lines.append("| liveMenu | group | localPath | shape | api | status |\n|---|---|---|---|---|---|\n")
    for e in catalog["ENT"]:
        lines.append(f"| {e['name']} | {e['group']} | `{e['path']}` | {e['shape']} | `{e['api']}` | {e['status']} |\n")
    lines.append(
        f"\n## 统计\n\n- GOV: {len(catalog['GOV'])}\n- ENT: {len(catalog['ENT'])}\n- TOTAL: {len(catalog['GOV']) + len(catalog['ENT'])}\n"
    )

    (ROOT / "crawl_output" / "10-全量对照矩阵.md").write_text("".join(lines), encoding="utf-8")
    fe = ROOT / "frontend" / "apps" / "admin" / "src" / "catalog"
    fe.mkdir(parents=True, exist_ok=True)
    (fe / "features.json").write_text(json.dumps(catalog, ensure_ascii=False, indent=2), encoding="utf-8")
    (ROOT / "backend" / "app" / "menu_catalog.json").write_text(json.dumps(catalog, ensure_ascii=False, indent=2), encoding="utf-8")
    print("GOV", len(catalog["GOV"]), "ENT", len(catalog["ENT"]))


if __name__ == "__main__":
    main()
